# Generated by Django 4.2.1 on 2023-05-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(max_length=6383),
        ),
    ]
