# Generated by Django 4.2.1 on 2023-05-08 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bidapp", "0002_alter_item_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="start_date",
        ),
    ]
